### ISSUE TITLE
README needs specific build instructions

### ISSUE THREAD

**Issue by posita** [squeaky-pl/portable-pypy#10]
It's not clear how the weekly or release builds are made. The ["How it is done" section](https://github.com/squeaky-pl/portable-pypy/tree/1afe3a3c0ad85dee5c17e9ce2dceb5369d925806#how-it-is-done) is not specific enough for repeatable results.

**Comment by posita** [comment]
One portable alternative that comes to mind is providing a [`Dockerfile`](https://docs.docker.com/reference/builder/) defining a build environment and a [`CMD`](https://docs.docker.com/reference/builder/#cmd) for producing a build (e.g.) in `/tmp/build`. Then anyone could make one by doing (e.g.):

`docker ... -v /tmp/build /host/path/for/build ... [IMAGE]`

**Comment by posita** [comment]
In that case, the `Dockerfile` would not only be "executable" to make builds, but it would serve as documentation for the process as well.

**Comment by posita** [comment]
@squeaky-pl, if you're interested, and if you can share with me your build instructions (script, etc.), I can try to make a centos5-based Dockerfile that makes them repeatable and a short README on how to use it.

**Comment by squeaky-pl** [comment]
Hi, sorry for making you wait so long, I needed to do some clean up on docker branch but now it is merged to master. Checkout `BUILD.rst`.

**Comment by posita** [comment]
> sorry for making you wait so long

I wasn't trying to rush you. :blush: I was only seeing if you wanted my assistance, but it looks like you were way ahead of things!

I hacked on your approach a bit and submitted #14 to make things (potentially) a little more friendly for others who want to build Portable PyPy in their own environments.

**Comment by techdragon** [comment]
@squeaky-pl has there been any progress on this or #14, I was hoping to be able to follow some instructions in order to replicate the build process in order to try building a different target than `pypystandalone`

**Comment by squeaky-pl** [comment]
@techdragon check https://github.com/squeaky-pl/portable-pypy/blob/master/BUILD.rst

**Comment by squeaky-pl** [comment]
I'm closing this since we have a BUILD.rst file that can guide you through the process now.
