### ISSUE TITLE
python 3.10 upgrade

### ISSUE THREAD

**Issue by sheepchen** [squeaky-pl/portable-pypy#101]
Hey,
is there a plan to upgrade the version to portable python 3.10 ?

**Comment by squeaky-pl** [comment]
Hey, this repository is no longer maintained. Part of this work was merged to upstream. The upstream lives at https://foss.heptapod.net/pypy/pypy. PyPy itself plans to support 3.10 at some point, it's mentioned in their latest blog post: https://www.pypy.org/posts/2022/07/ddorf-sprint-sep-2022.html. For further questions I would suggested speaking with PyPy developers themselves: https://www.pypy.org/posts/2021/05/pypy-irc-moves-to-libera-chat.html.
