### ISSUE TITLE
ssh to Resource Manager on Hadoop 2

### ISSUE THREAD

**Issue by davidmarin** [squeaky-pl/portable-pypy#11]
Hadoop 2 (YARN) doesn't have a "Job Tracker"; it has a "Resource Manager". This performs much the same function, but it's on a different default port, and formats the page differently.

We need to:
 * detect which version of Hadoop we're using
 * connect to the correct port
 * correctly parse out Map/Reduce %

**Comment by squeaky-pl** [comment]
I think you didnt mean to report this here?

**Comment by davidmarin** [comment]
Sorry! Meant to file this on https://github.com/Yelp/mrjob, not here.
