### ISSUE TITLE
2.6 Released! Time for new portable-pypy!

### ISSUE THREAD

**Issue by v3ss0n** [squeaky-pl/portable-pypy#13]
+1

**Comment by squeaky-pl** [comment]
ETA 12h

**Comment by squeaky-pl** [comment]
Actually 2.6 was not released, will be released towards end of the week. Putting this on hold until final revision is confirmed.
```
<mattip> squeaky_pl: hold off a bit, there will be updates before final 2.6.0
```

**Comment by v3ss0n** [comment]
Oops , okay  thanks! :)

**Comment by v3ss0n** [comment]
Oops  okay! thanks

**Comment by squeaky-pl** [comment]
I am translating, ETA 2h

**Comment by v3ss0n** [comment]
thanks a lot , You are awesome! waiting to upgrade.

**Comment by squeaky-pl** [comment]
Done.

**Comment by v3ss0n** [comment]
+1 , its working very well!
