### ISSUE TITLE
Come up with a security related updates strategy

### ISSUE THREAD

**Issue by squeaky-pl** [squeaky-pl/portable-pypy#16]
Since OpenSSL is bundled and I already found out that it is impossible to deliver a binary that links cleanly against all the supported OSes I should come up with a security updates strategy.

I could for example maintain the last version of PyPy against all known security related problems and rebuild each time that happens. I could include versions of bundled libraries inside interactive Python banner prompt.

The open question for me is how do I communicate that updates to downstream users and what is the best way to watch vulnerabilities in all bundled software.

**Comment by v3ss0n** [comment]
a build system with updated packages?
