### ISSUE TITLE
Portable debug builds

### ISSUE THREAD

**Issue by DRMacIver** [squeaky-pl/portable-pypy#19]
Would it be possible to also do debug builds of the portable pypys?

My use case:

I'm using the portable pypys (via pyenv) as the basis for the pypy runner in my CI build.

Unfortunately my build triggers intermittent segfaults in pypy. These are very hard to debug with the normal release builds, so I'd like to run a parallel version of the build with a debug version of pypy, but there's currently no remotely convenient way to do that.

**Comment by Julian** [comment]
+1

**Comment by squeaky-pl** [comment]
PyPy as of now (5.10.0) ships debug symbols along normal release binaries.
