### ISSUE TITLE
Time for pypy 5.0!

### ISSUE THREAD

**Issue by v3ss0n** [squeaky-pl/portable-pypy#21]
Released!

**Comment by barahilia** [comment]
It looks like the 5.0 release has being [prepared](https://bitbucket.org/pypy/pypy/history-node/7395989c4270/pypy/doc/release-5.0.0.rst) for the last 5 days and even mentioned in the official [docs](http://doc.pypy.org/en/latest/release-5.0.0.html) but isn't not ready yet - no tag or [download](https://bitbucket.org/pypy/pypy/downloads) available.

**Comment by flibustenet** [comment]
Download of 5.0 are available (since 10 march)
Thanks in advance !

**Comment by squeaky-pl** [comment]
ETA 24h

**Comment by kikocorreoso** [comment]
\o/

Many thanks!!!!

**Comment by squeaky-pl** [comment]
The 64-bit builds are already available:

https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-5.0-linux_x86_64-portable.tar.bz2

Keeping it open until I have 32 bit done.

**Comment by squeaky-pl** [comment]
This is now done.

**Comment by kikocorreoso** [comment]
This is awesome!!!

Thank you so much!!!!

**Comment by v3ss0n** [comment]
awesome man , !
