### ISSUE TITLE
bin/pypy: symbol lookup error: <path_to_portable_pypy>/libpypy-c.so: undefined symbol: SSL_CTX_set_alpn_protos

### ISSUE THREAD

**Issue by rogererens** [squeaky-pl/portable-pypy#24]
Hi,
thanks for your portable-pypy bundle!
I want to use the pypy-5.0.1-linux_x86_64-portable version on our RHEL6.4 server for our intranet webserver.

Except for the system's openssl version, my employer lets me choose to 'enable' either a 32 or 64 bit version of openssl 1.0.0d, of which I need the latter for other packages. So I have 'enable'd the 64 bit version.

Now, when I activate a virtualenv, created with the portable pypy's virtualenv command, and try to start the pypy in it, I get the abovementioned error and the pypy interpreter does not start up.

I don't get the error when I 'enable' the 32 bit version, or use the system's version. But that frustrates the use of other packages. :-(

Do you have an idea why this happens and what can be done about it? I had hoped that my virtualenv would use the openssl that is included in the portable pypy.

Thanks for any ideas or hints,

**Comment by squeaky-pl** [comment]
Hey, as specified in the README portable PyPy bundles `openssl` inside the tarball under the `lib` directory. It SHOULD NOT use system-wide openssl installation, it's impossible to ship portable binary relaying on system-wide `openssl` installation, but from what I understand you it is trying to use system-wide `openssl`. 

The said bundled `openssl` sits here in the freshly unpacked tarball (among other libs):

```
ls -lha pypy-5.0.1-linux_x86_64-portable/lib/
lrwxrwxrwx 1 squeaky squeaky   18 Mar 19 17:06 libcrypto.so -> libcrypto.so.1.0.0
-r-xr-xr-x 1 squeaky squeaky 2.4M Mar 19 17:06 libcrypto.so.1.0.0
lrwxrwxrwx 1 squeaky squeaky   15 Mar 19 17:06 libssl.so -> libssl.so.1.0.0
-r-xr-xr-x 1 squeaky squeaky 452K Mar 19 17:06 libssl.so.1.0.0
```

If I actually trace the libraries that `bin/pypy` uses 

```
ldd pypy-5.0.1-linux_x86_64-portable/bin/pypy 
	libssl.so.1.0.0 => /home/squeaky/workspace/portable-pypy/pypy-5.0.1-linux_x86_64-portable/bin/../lib/libssl.so.1.0.0 (0x00007f03d45c1000)
	libcrypto.so.1.0.0 => /home/squeaky/workspace/portable-pypy/pypy-5.0.1-linux_x86_64-portable/bin/../lib/libcrypto.so.1.0.0 (0x00007f03d416e000)
```

You can see it resolves that libraries relatively to the tarball.
Can you first confirm that you can run 64 bit portable pypy fine without `virtualenv`?

**Comment by rogererens** [comment]
I appreciate your help. I indeed understood from the README that portable PyPy should not care about the other openssl bundles on the system, which is why I am surprised by this issue.

To answer your questions:
1. I cannot with 'our' 64bit openssl 'enabled'.
I can with the 32bit version of the company, or system stock version:
>  %  (TST)> bin/pypy
> Python 2.7.10 (bbd45126bc691f669c4ebdfbd74456cd274c6b92, Mar 19 2016, 10:51:04)
> [PyPy 5.0.1 with GCC 4.9.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.

2. Using (with the 32bit openssl enabled)
> <path_to_portable_pypy>/bin/virtualenv-pypy zz-venv

3. 15.0.1
4. Your portable PyPy bundle

Your commands repeated here:
> /MCM_Test_Tool/rerens/.try/pypy501
> bash-4.1$ ls -lha lib
> total 7.2M
> drwxrwxrwx. 4 rerens asd 4.0K Mar 19 17:06 .
> drwxrwxrwx. 9 rerens asd 4.0K Mar 19 17:06 ..
> lrwxrwxrwx. 1 rerens asd   18 Mar 19 17:06 libcrypto.so -> libcrypto.so.1.0.0
> -rwxrwxrwx. 1 rerens asd 2.4M Mar 19 17:06 libcrypto.so.1.0.0
> lrwxrwxrwx. 1 rerens asd   13 Mar 19 17:06 libexpat.so -> libexpat.so.1
> -rwxrwxrwx. 1 rerens asd 204K Mar 19 17:06 libexpat.so.1
> lrwxrwxrwx. 1 rerens asd   11 Mar 19 17:06 libffi.so -> libffi.so.6
> -rwxrwxrwx. 1 rerens asd  52K Mar 19 17:06 libffi.so.6
> lrwxrwxrwx. 1 rerens asd   12 Mar 19 17:06 libgdbm.so -> libgdbm.so.4
> -rwxrwxrwx. 1 rerens asd  57K Mar 19 17:06 libgdbm.so.4
> lrwxrwxrwx. 1 rerens asd   15 Mar 19 17:06 libsqlite3.so -> libsqlite3.so.0
> -rwxrwxrwx. 1 rerens asd 967K Mar 19 17:06 libsqlite3.so.0
> lrwxrwxrwx. 1 rerens asd   15 Mar 19 17:06 libssl.so -> libssl.so.1.0.0
> -rwxrwxrwx. 1 rerens asd 452K Mar 19 17:06 libssl.so.1.0.0
> -rwxrwxrwx. 1 rerens asd 1.7M Mar 19 17:06 libtcl.so
> -rwxrwxrwx. 1 rerens asd 1.4M Mar 19 17:06 libtk.so
> drwxrwxrwx. 6 rerens asd 4.0K Mar 13 01:08 tcl
> drwxrwxrwx. 6 rerens asd 4.0K Mar 13 01:09 tk

and (with 32bit openssl):
> bash-4.1$ ldd bin/pypy
> 	linux-vdso.so.1 =>  (0x00007fff44ec1000)
> 	libpypy-c.so => /MCM_Test_Tool/rerens/.try/pypy501/bin/libpypy-c.so (0x00007f98290b6000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00000038c0200000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00000038bfe00000)
> 	libutil.so.1 => /lib64/libutil.so.1 (0x00000038c2600000)
> 	libz.so.1 => /lib64/libz.so.1 (0x00000038c0e00000)
> 	libbz2.so.1 => /lib64/libbz2.so.1 (0x00000038c4e00000)
> 	libssl.so.1.0.0 => /MCM_Test_Tool/rerens/.try/pypy501/bin/../lib/libssl.so.1.0.0 (0x00007f9828e3a000)
> 	libcrypto.so.1.0.0 => /MCM_Test_Tool/rerens/.try/pypy501/bin/../lib/libcrypto.so.1.0.0 (0x00007f98289e7000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00000038bfa00000)
> 	libexpat.so.1 => /MCM_Test_Tool/rerens/.try/pypy501/bin/../lib/libexpat.so.1 (0x00007f98287b4000)
> 	librt.so.1 => /lib64/librt.so.1 (0x00000038c0600000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00000038c0a00000)
> 	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00000038c3a00000)
> 	libffi.so.6 => /MCM_Test_Tool/rerens/.try/pypy501/bin/../lib/libffi.so.6 (0x00007f98285a5000)
> 	libncurses.so.5 => /lib64/libncurses.so.5 (0x00007f9828383000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00000038bf600000)
> 	libfreebl3.so => /lib64/libfreebl3.so (0x00000038c1a00000)
> 	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00000038c1600000)

and (with 64bit openssl; Note that e.g. libssl.so.1.0.0 is now linking to a 64bit object):
> bash-4.1$ ldd bin/pypy
> 	linux-vdso.so.1 =>  (0x00007fff076e2000)
> 	libpypy-c.so => /MCM_Test_Tool/rerens/.try/pypy501/bin/libpypy-c.so (0x00007f4b29784000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00000038c0200000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00000038bfe00000)
> 	libutil.so.1 => /lib64/libutil.so.1 (0x00000038c2600000)
> 	libz.so.1 => /lib64/libz.so.1 (0x00000038c0e00000)
> 	libbz2.so.1 => /lib64/libbz2.so.1 (0x00000038c4e00000)
> 	libssl.so.1.0.0 => /home/rerens/.caddir/RHEL6/cadlib/libssl.so.1.0.0 (0x00007f4b2951f000)
> 	libcrypto.so.1.0.0 => /home/rerens/.caddir/RHEL6/cadlib/libcrypto.so.1.0.0 (0x00007f4b29179000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00000038bfa00000)
> 	libexpat.so.1 => /MCM_Test_Tool/rerens/.try/pypy501/bin/../lib/libexpat.so.1 (0x00007f4b28f46000)
> 	librt.so.1 => /lib64/librt.so.1 (0x00000038c0600000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00000038c0a00000)
> 	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00000038c3a00000)
> 	libffi.so.6 => /MCM_Test_Tool/rerens/.try/pypy501/bin/../lib/libffi.so.6 (0x00007f4b28d37000)
> 	libncurses.so.5 => /lib64/libncurses.so.5 (0x00007f4b28b15000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00000038bf600000)
> 	libfreebl3.so => /lib64/libfreebl3.so (0x00000038c1a00000)
> 	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00000038c1600000)

**Comment by squeaky-pl** [comment]
OK, it looks like you have some mechanism enabled that rewrites the linker paths.

What are those `.caddir cadlib`? directories, these are not standard linux direcotires to look for shared objects, it looks like you have some `LD_PRELOAD` environment variable set in your environment that forces the dynamic linker to look there?

can you see in `env` if any of enviornment variables that affect dynamic linking are set: http://man7.org/linux/man-pages/man8/ld.so.8.html. They are listed here under `ENVIRONMENT` variables. `LD_LIBRARY_PATH` `LD_PRELOAD` `LD_AOUT_LIBRARY_PATH` `LD_AOUT_PRELOAD` `LD_ORIGIN_PATH` are the most obvious to look for.

**Comment by rogererens** [comment]
Those directories are indeed created by our internal tooling, allowing us to quickly change between versions of a library/package/program.

Thanks for your nudge into the right direction!

I can now start pypy within a bash subshell where LD_LIBRARY_PATH is cleared:

> (zz-venv) bash-4.1$ pypy
pypy: symbol lookup error: /zz-venv/bin/libpypy-c.so: undefined symbol: SSL_CTX_set_alpn_protos
(zz-venv) bash-4.1$ (LD_LIBRARY_PATH= ;pypy)
Python 2.7.10 (bbd45126bc691f669c4ebdfbd74456cd274c6b92, Mar 19 2016, 10:51:04)
[PyPy 5.0.1 with GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>>

Hope this info helps you making your portable pypy even more robust!

**Comment by squeaky-pl** [comment]
Well, I can do nothing about it. By using `LD_LIBRARY_PATH` you explicitely forced dynamic linker to look at certain places, this will break many programs, not only portable pypy. I consider this resolved.
