### ISSUE TITLE
error loading shared library on Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by carljm** [squeaky-pl/portable-pypy#27]
Unpacking `pypy-5.1.1-linux_i686-portable` and running pypy results in `pypy: error while loading shared libraries: libbz2.so.1: cannot open shared object file: No such file or directory` on Ubuntu 16.04 Xenial.

**Comment by squeaky-pl** [comment]
Are you running some stripped down version of Ubutnu? 

It looks like Ubuntu has this file: http://packages.ubuntu.com/xenial/amd64/libbz2-1.0/filelist

```
/lib/x86_64-linux-gnu/libbz2.so.1
/lib/x86_64-linux-gnu/libbz2.so.1.0
/lib/x86_64-linux-gnu/libbz2.so.1.0.4
/usr/share/doc/libbz2-1.0/changelog.Debian.gz
/usr/share/doc/libbz2-1.0/copyright
```

**Comment by squeaky-pl** [comment]
Are you actually running i686 build on x86_64 platform maybe?

**Comment by squeaky-pl** [comment]
@carljm I cannot reproduce this. I downloaded Ubuntu Xenial Server i386 from http://releases.ubuntu.com/16.04/ubuntu-16.04-server-i386.iso

```
uname -a
Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:34:49 UTC 2016 i686 i686 i686 GNU/Linux

pypy-5.1.1-linux_i686-portable/bin/pypy 
Python 2.7.10 (b0a649e90b6642251fb4a765fe5b27a97b1319a9, May 05 2016, 17:21:13)
[PyPy 5.1.1 with GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> 

```

Can you please give me exact steps to reproduce?

**Comment by carljm** [comment]
@squeaky-pl I am extremely embarrassed, and very sorry to have wasted your time. The issue was indeed that I was unpacking the i686 build on an x64 system. No idea how I failed to notice that. Using the correct build works fine.

**Comment by carljm** [comment]
(And sorry for the slow response this week, been at PyCon all week. Let me know if you're coming to a future PyCon, I'll be happy to buy you a drink to make up for wasting your time with this issue!)
