### ISSUE TITLE
How much of manual steps needed to build nightly? Can this be automated?

### ISSUE THREAD

**Issue by v3ss0n** [squeaky-pl/portable-pypy#33]
Squeaky , I am thinking of looking ways to automate this (for example , nightly portable-pypy builds with build-bot ) . is that possible?

**Comment by squeaky-pl** [comment]
For the build steps see: https://github.com/squeaky-pl/portable-pypy/blob/master/BUILD.rst

It's possible to automate this but I personally dont have infrastructure to do so nor time to invest in maintainig it.

**Comment by v3ss0n** [comment]
It seems that every step there can easily be automated. I can do the automation script. I will check with pypy guys for infrastructure of build-bot.

**Comment by v3ss0n** [comment]
There is no manual patching needed right?

**Comment by squeaky-pl** [comment]
There are several patches and hacks, look through through the `build` `build_deps` and `package` script if you wanna know details. But I do not do manual patching.
