### ISSUE TITLE
5.4.1 inbound! 

### ISSUE THREAD

**Issue by v3ss0n** [squeaky-pl/portable-pypy#34]
Check'em

**Comment by squeaky-pl** [comment]
ETA 24h

**Comment by squeaky-pl** [comment]
x86_64  landed https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-5.4.1-linux_x86_64-portable.tar.bz2

**Comment by v3ss0n** [comment]
Awesome , we don't neeed automated build-bot anyone , you are the machine :P

**Comment by squeaky-pl** [comment]
And i686 done, closing
