### ISSUE TITLE
New Pypy3.3-5.5 alpha binaries released

### ISSUE THREAD

**Issue by Samureus** [squeaky-pl/portable-pypy#35]
http://pypy.org/download.html

Thanks in advance!

**Comment by squeaky-pl** [comment]
ETA 24h

**Comment by squeaky-pl** [comment]
64bit done: https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.3-5.5-alpha-20161013-linux_x86_64-portable.tar.bz2

**Comment by squeaky-pl** [comment]
and 32bit as well.
