### ISSUE TITLE
How can I compile pypy3?

### ISSUE THREAD

**Issue by QuasarPark** [squeaky-pl/portable-pypy#36]
Hello!

I have some trouble with pre-compiled version of pypy3, so I want to evaluate that through portable-pypy.

My OS version is CentOS Linux release 7.2.1511 and kernel version 3.10.0-327.28.2.el7.x86_64. If I want to compile pypy3, How can I get it?

Example step in BUILD.rst is only handled pypy version. (cpython2)
Please some advice to me!

**Comment by squeaky-pl** [comment]
You would do exactly like for PyPy implementing Python 2 but at the translate step you would pass a tag from `py3.5` branch for example:
```
docker run --rm `ABI=64 ./runopt.sh` portable-pypy ./build py3.5
```

**Comment by TiberiumPY** [comment]
@QuasarPark but if you want beta-stable PyPy3 v5.5.0 - you need to pass a tag 'py3k' instead of 'py3.5'

**Comment by QuasarPark** [comment]
Thanks for your advice! I'll try it.
