### ISSUE TITLE
portable pypy 5.4.1 doesn't have socket.SO_REUSEPORT

### ISSUE THREAD

**Issue by thestick613** [squeaky-pl/portable-pypy#44]
stock pypy 5.4.1

```
Python 2.7.10 (5.4.1+dfsg-1~ppa1~ubuntu14.04, Sep 06 2016, 23:11:48)
[PyPy 5.4.1 with GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import socket
>>>> socket.SO_REUSEADDR
2
>>>> socket.SO_REUSEPORT
15

```

portable pypy 5.4.1

```
Python 2.7.10 (0e2d9a73f5a1818d0245d75daccdbe21b2d5c3ef, Sep 07 2016, 14:23:17)
[PyPy 5.4.1 with GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import socket
>>>> socket.SO_REUSEADDR
2
>>>> socket.SO_REUSEPORT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SO_REUSEPORT'
>>>> 

```

**Comment by squeaky-pl** [comment]
SO_REUSEPORT is realtively new and probably not exposed by underlying kernel/glibc headers on Centos 5. There is probably some ugly way to force it though

**Comment by squeaky-pl** [comment]
I'll keep it open until I find a solution, probably there are more symbols like that. Patching socket, looking up kernel version on an import and then conditionally exposing them would be fine. Afterall those are integers with symbolic names.

**Comment by squeaky-pl** [comment]
For the reference here is the list: http://man7.org/linux/man-pages/man7/socket.7.html

**Comment by squeaky-pl** [comment]
I compared what portable PyPy has with what CPython exposes on modern kernel, I added a patch to socket.py to expose those depending on the kernel version they were introduced.

You can see the patch here: https://github.com/squeaky-pl/portable-pypy/commit/49cd63f545094316b1752978c751fc485c4e13bd

This will make it to the future portable PyPy release/

**Comment by thestick613** [comment]
Thank you for your work. I eventually decided not to use portable pypy - because there were other things not working besides SO_REUSEPORT. Do you want me to open new issues with those things as well?

**Comment by TiberiumPY** [comment]
@thestick613 it's always good to have a list of known bugs, so @squeaky-pl can eventually fix them

**Comment by squeaky-pl** [comment]
@thestick613 please report them.
