### ISSUE TITLE
5.7 release

### ISSUE THREAD

**Issue by squeaky-pl** [squeaky-pl/portable-pypy#45]
in progress

**Comment by dansut** [comment]
5.7?

**Comment by squeaky-pl** [comment]
3.5 done: https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.7-beta-linux_x86_64-portable.tar.bz2

**Comment by squeaky-pl** [comment]
2.7 done.

I decided to stop providing 32 bit builds since they made less than 1% of downloads.
