### ISSUE TITLE
Distribute PyPy 5.7.1 x86/i686

### ISSUE THREAD

**Issue by ofek** [squeaky-pl/portable-pypy#50]
Then https://github.com/pypa/manylinux/pull/105 could fully support PyPy.

**Comment by squeaky-pl** [comment]
The last version that I did that for was 5.7. I am no longer gonna support i686.

**Comment by squeaky-pl** [comment]
Also note that 5.7.1 was the last release to build against Centos 5. All the future releases will be built against Centos 6.

**Comment by ofek** [comment]
Ok then, thanks!
