### ISSUE TITLE
Bug - Platform version in socket.append.py

### ISSUE THREAD

**Issue by audiolion** [squeaky-pl/portable-pypy#54]
On my server RHEL 7 the kernel version is "4.1.39_1"

The code:
https://github.com/squeaky-pl/portable-pypy/blob/master/socket.append.py#L13

splits on `-`, as a result it tries to `map(int, '39_1')` and fails because it can't convert that to an `int`, I had to edit the source code to split on `_` to use the portable pypy install.

**Comment by squeaky-pl** [comment]
Oh. I knew I am gonna regret this, this is needed though because not all of those symbols will be available on the platform where it is translated. Gonna fix ASAP.

**Comment by squeaky-pl** [comment]
I issued a bugfix release. I dont have a machine with RHEL. Can you try to `import socket` on:

https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.8-1-beta-linux_x86_64-portable.tar.bz2

and

https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-5.8-1-linux_x86_64-portable.tar.bz2

**Comment by audiolion** [comment]
Yeah its working, now it outputs `(4, 1, 39, 1)`

**Comment by squeaky-pl** [comment]
Thanks for the report and testing.
