### ISSUE TITLE
pypy 2.5.0 is out

### ISSUE THREAD

**Issue by cactus** [squeaky-pl/portable-pypy#6]
I am sure you already saw, but if not -- http://morepypy.blogspot.com/2015/02/pypy-250-released.html

ps. Thanks for portable-pypy!

**Comment by squeaky-pl** [comment]
Working on release. ETA 24h

**Comment by masolit** [comment]
thx :+1:

**Comment by masolit** [comment]
@squeaky-pl  thx :+1:

**Comment by v3ss0n** [comment]
@squeaky-pl  thanks , wiating for it.

**Comment by squeaky-pl** [comment]
Probably you are waiting for 64 bit builds but 32 bit one is now available now at: https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.5-linux_i686-portable.tar.bz2
64 bit ones are coming in <10hours

**Comment by squeaky-pl** [comment]
The builds are done now. Refer to  https://github.com/squeaky-pl/portable-pypy to get x86_64 build. Closing.

**Comment by cactus** [comment]
:+1: thank you!

**Comment by v3ss0n** [comment]
@squeaky-pl  THANKS A LOT!
