### ISSUE TITLE
Release archives with full semantic version number on minor releases

### ISSUE THREAD

**Issue by haz-mat** [squeaky-pl/portable-pypy#61]
It would be somewhat helpful for programmatically installing portable pypy to always be able to expect all 3 version numbers (major.minor.patch) in the archive file name. For instance, it would be helpful downloading `pypy-5.9-linux_x86_64-portable.tar.bz2` as `pypy-5.9.0-linux_x86_64-portable.tar.bz2`. 

Thanks for considering. 

PS: portable pypy is very useful thanks for awesome work.

**Comment by squeaky-pl** [comment]
As of 5.10.0 the versions contain 3 numbers.
