### ISSUE TITLE
Build pypy59 on MAC with docker

### ISSUE THREAD

**Issue by blacksun1977** [squeaky-pl/portable-pypy#63]
When I build pypy59 on my MAC，the "build_deps" always with errors.
`
+ make -j4
make: *** No targets specified and no makefile found.  Stop.
`
i am not sure how the error happend,
so i install a VirtualBox , got an CentOs 6.8 virtual machine,
first, i put source in a "share folder" to build pypy59, the same error happend,

second, i copy the source inside the virtual machine, verything is OK !

so i am confused, the "build" is under the Docker, 
how the difference of  "MAC host" and "VirtualBox CentOs 6.8 virtual machine with share folder" 
and "VirtualBox CentOs 6.8 virtual machine inside disk",

the only difference is think is the "file system", dose the "make" dependent the file system ?

**Comment by squeaky-pl** [comment]
Sorry, I dont know anything about make on MacOS and being fs dependent. And nobody answered here in more than one year so I am gonna close this.
