### ISSUE TITLE
support 5.10.1

### ISSUE THREAD

**Issue by mattip** [squeaky-pl/portable-pypy#65]
A bugfix PyPy3.5 v5.10.1 has been tagged and will be released soon. Would it be possible to get the version here as well? The [changes](http://doc.pypy.org/en/latest/release-v5.10.1.html) for linux are very minor.

**Comment by squeaky-pl** [comment]
Hey Matti, I've gonna pull it today at night European time or tomorrow in
the evening. Thanks for letting me know.

**Comment by mattip** [comment]
ok, thanks
