### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by mictadlo** [squeaky-pl/portable-pypy#66]
Hi,
I tried to create for PYPY and Conda package [here](https://github.com/conda-forge/staged-recipes/pull/5027). Conda is an open source package management system and environment management system that runs on Windows, macOS and Linux.

Unfortunately, the package has failed and I just wonder whether you maybe know what is the reason.

Thank you in advance.

Michal

**Comment by squeaky-pl** [comment]
I dont quite understand what you are trying to accomplish. This is a binary x86_64 build of PyPy for Linux.

I looked into the travis output for the pull you linked, it has:

```TEST START: /Users/travis/miniconda/conda-bld/osx-64/pypy2-5.10.0-0.tar.bz2```

So it looks like it's trying to do something on  OSX and of course it cannot work.

**Comment by mictadlo** [comment]
Thank you for pointing this out. Do I need the below [packages](https://github.com/mictadlo/staged-recipes/blob/dbe2e52450035ca1c8ef9ddf4eb3ed66a311c568/recipes/pypy/meta.yaml#L20) or are these already part of your package?

        - openssl
        - sqlite
        - system
        - tk
        - zlib
        - bzip2
        - libffi
        - expat
        - ncurses
        - gdbm
        - xz
        - expat

Thank you in advance.

Michal

**Comment by mictadlo** [comment]
I read your project and my understanding none of the above dependencies are necessary.

**Comment by squeaky-pl** [comment]
I dont know what `system` means, `zlib` and `bzip2` libraries do not need to be bundled because it's ABI/API didnt change for years, everything else is bundled.

**Comment by mictadlo** [comment]
Hi, PYPY 2.7 can be installed by `conda install pypy2.7`. Maybe you could keep the conda package up to date and maybe you could include pypy3?

**Comment by squeaky-pl** [comment]
I've seen they added pypy3 build from source recipe. I have no experience nor much interest in conda-forge so I would prefer their community to take care of the builds - whatever they choose as down-stream.
