### ISSUE TITLE
pypy 6.0 is being released

### ISSUE THREAD

**Issue by mattip** [squeaky-pl/portable-pypy#74]
It would be nice to get updated binaries, thanks

**Comment by squeaky-pl** [comment]
3.5 6.0.0 release is ready: https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-6.0.0-linux_x86_64-portable.tar.bz2

2.7 will follow in couple of hours

**Comment by squeaky-pl** [comment]
and 2.7 is done:

https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-6.0.0-linux_x86_64-portable.tar.bz2

**Comment by mattip** [comment]
Thanks!
