### ISSUE TITLE
PyPy 2.5.1 is released

### ISSUE THREAD

**Issue by joshfriend** [squeaky-pl/portable-pypy#8]
http://doc.pypy.org/en/latest/release-2.5.1.html

In pyenv, some users will see an error when trying to install 2.5.1 since the portable version is not available yet.
yyuu/pyenv#340

**Comment by squeaky-pl** [comment]
ETA 24h

**Comment by v3ss0n** [comment]
this is ready?

**Comment by squeaky-pl** [comment]
Not yet, there are some unexpected i ssues with 2.5.1. Investigating with PyPy team.

**Comment by squeaky-pl** [comment]
The issues have been resolved with help of PyPy team and the build landed. You can grab it from README.md. Thanks for patience.

**Comment by v3ss0n** [comment]
Thanks a lot!Squeaky!

**Comment by joshfriend** [comment]
Very nice, Thanks!
