### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by geekofalltrades** [squeaky-pl/portable-pypy#82]
This repo doesn't have a license, which makes using your builds difficult for companies with concerned lawyers. Can you please add a license to your repo? PyPy itself uses the MIT license, so that might be a good choice.

https://bitbucket.org/pypy/pypy/src/default/LICENSE?fileviewer=file-view-default

**Comment by squeaky-pl** [comment]
Thanks for reminding me, this is resolved.
