### ISSUE TITLE
Portable CPython

### ISSUE THREAD

**Issue by alexprengere** [squeaky-pl/portable-pypy#83]
I have used portable-pypy for years now, without any issues. This is the first project I go to when a Pypy release is out, it is *truly* awesome.
I have not found a similar project for CPython (perhaps I missed it), is there a technical limitation that prevents building portable binaries for CPython? If not, would you be interested in building the latest 2.x and 3.x branches of CPython as well?

**Comment by SemenMartynov** [comment]
I did a portable CPython3.7 based on this project.
If this is interesting, I can release it out.

**Comment by squeaky-pl** [comment]
While a cool idea I don't have time to maintain myself portable CPython. If @SemenMartynov is up to it and there's enough interest I'd say there's nothing here for myself to do.
