### ISSUE TITLE
pypy 7.0 is being released

### ISSUE THREAD

**Issue by antocuni** [squeaky-pl/portable-pypy#86]
We will release PyPy 7.0.0 shortly, would be nice to have portable binaries as well.
These are the links to the appropriate tags:
https://bitbucket.org/pypy/pypy/commits/tag/release-pypy2.7-v7.0.0
https://bitbucket.org/pypy/pypy/commits/tag/release-pypy3.5-v7.0.0
https://bitbucket.org/pypy/pypy/commits/tag/release-pypy3.6-v7.0.0

Thanks!

**Comment by squeaky-pl** [comment]
Hi, thanks for letting me know, I will start translating now.

**Comment by antocuni** [comment]
Any news on this? Sorry for pushing, I ask only because the binary wheels produced by
https://github.com/antocuni/pypy-wheels depend on portable PyPy, and I would like to release wheels for PyPy 7.0 soon :)

**Comment by squeaky-pl** [comment]
@antocuni I already did the binaries, I just waited for oficial release to publish them. One sec to update the front page.

**Comment by squeaky-pl** [comment]
@antocuni all done now.

**Comment by antocuni** [comment]
thank you very much!
