### ISSUE TITLE
Any plans of building ARM binaries?

### ISSUE THREAD

**Issue by naclander** [squeaky-pl/portable-pypy#89]
For Raspberry/Banana Pis and such, or any other fruits.

**Comment by squeaky-pl** [comment]
I dont have myself access to any such devices and even though I could probably use some kind of emulator I am skeptic about doing this myself as I have no real interest in those platforms and I bet they come with their own ABI peculiarities that I am not aware of.

Said that if somebody commits to building, testing and maintaining those platforms for a longer period of time I would be open to accepting patches. Or even somebody could fork this to do such work fully on their behalf.

**Comment by naclander** [comment]
@squeaky-pl that sounds good, thanks for great package so far.

**Comment by ppouliot** [comment]
Unfortunately I may not be able to do the development work but there's a good chance I could get you access to some Ampere ARM servers for development and testing effort.

**Comment by squeaky-pl** [comment]
closing as the patches have been merged to upstream PyPy.

**Comment by probonopd** [comment]
fwiw, Travis CI offers free ARM workers.
