### ISSUE TITLE
New 7.1 tags for pypy2.7 and pypy3.6

### ISSUE THREAD

**Issue by mattip** [squeaky-pl/portable-pypy#90]
I have moved the release-pypy2.7-v7.1.0 and release-pypy3.6-v7.1.0 tags to fix some small issues. Do you think it would be possible to build portable packages for an upcoming release?

**Comment by squeaky-pl** [comment]
Yes, I will get them out tomorrow.

**Comment by squeaky-pl** [comment]
For people waiting, I want be able to make it today. I have too many other things happening this week. Will try to find some time tomorrow.

**Comment by squeaky-pl** [comment]
Done.
