### ISSUE TITLE
pypy3.x 7.x readline warning in virtualenv

### ISSUE THREAD

**Issue by jjsp556** [squeaky-pl/portable-pypy#92]
Using pypy3.6-7.1.1-beta-linux_x86_64-portable or pypy3.5-7.0.0-linux_x86_64-portable, a readline warning (/home/user/pypyvenv/lib-python/3/site.py:703: UserWarning: readline.read_init_file() not implemented) is thrown when entering an interpreter in a virtual environment. The warning is only thrown in a virtualenv. I get this warning in both Ubuntu 18.04 and Centos 7. I do not see this warning in pypy3.5-6.0.0-linux_x86_64-portable. Here are the steps taken to produce this warning. 

user@host:~$ pypy3.6-7.1.1-beta-linux_x86_64-portable/bin/virtualenv-pypy ~/pypyvenv
Using base prefix '/home/user/Downloads/pypy3.6-7.1.1-beta-linux_x86_64-portable'
New pypy executable in /home/user/pypyvenv/bin/pypy
Installing setuptools, pip, wheel...
done.

user@host:~$ source ~/pypyvenv/bin/activate

(pypyvenv) user@host:~$ python
Python 3.6.1 (784b254d669919c872a505b807db8462b6140973, Apr 16 2019, 18:18:28)
[PyPy 7.1.1-beta0 with GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
/home/user/pypyvenv/lib-python/3/site.py:703: UserWarning: readline.read_init_file() not implemented
  readline.read_init_file()
And now for something completely different: ``happy new year''

**Comment by squeaky-pl** [comment]
This was already reported against PyPy project itself.

It was decided that nothing will be done about this since PyPy does not use readline at all. This happens on latet virtualenv with latest PyPy.

If you still think this is a bug you need to report this against PyPy.

**Comment by squeaky-pl** [comment]
Looks like it was in the end resolved but you will need to wait for 7.2:

https://bitbucket.org/pypy/pypy/issues/2983/regression-in-72-readline-not-working

**Comment by bjmgeek** [comment]
I'm still seeing this issue in 7.2

    Python 3.6.9 (5da45ced70e515f94686be0df47c59abd1348ebc, Oct 17 2019, 22:59:56)
    [PyPy 7.2.0 with GCC 8.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    /home/bminton/venv-pypy3-portable/lib-python/3/site.py:683: UserWarning: readline.read_init_file() not implemented
      readline.read_init_file()
    >>>>

**Comment by squeaky-pl** [comment]
It seems that is has not been fixed in the end but it's an upstream "problem":

https://bitbucket.org/pypy/pypy/src/5da45ced70e515f94686be0df47c59abd1348ebc/lib_pypy/pyrepl/readline.py#lines-434

but it's safe to ignore unless you realy on readline init file to do anything.
