### ISSUE TITLE
Provide a python3 link

### ISSUE THREAD

**Issue by akiross** [squeaky-pl/portable-pypy#93]
Hello,
I noticed that pypy3.6 is providing a `python` symlink to `pypy3.6`, but there are no `python3` and `python3.6` symlinks. Is this the desired behavior?

I come to ask after installing pypy3.6-7.1.1 using pyenv (see [this issue](https://github.com/pyenv/pyenv/issues/1393)), which will not update the `python3` executable since none is provided by portable-pypy. In this way, if I want to set pypy as the default version, the `python` and `python3` commands will refer to two different implementations.

Therefore I think it would be better to provide the python3 symlink as well, if this is compliant with PEP-394 (as I think it is).

**Comment by squeaky-pl** [comment]
This sounds reasonable. I will try to provide this next time a PyPy release is being built.

**Comment by squeaky-pl** [comment]
This was fixed in 3.6-7.2
