### ISSUE TITLE
PyPy 7.2

### ISSUE THREAD

**Issue by antocuni** [squeaky-pl/portable-pypy#94]
PyPy 7.2 has been [released](https://morepypy.blogspot.com/2019/10/pypy-v72-released.html).
Could you please add it to the builds?

**Comment by gaborbernat** [comment]
Ping on this 😄

**Comment by davit555** [comment]
Any update ? )

**Comment by squeaky-pl** [comment]
You can already find 3.6 in here https://github.com/squeaky-pl/portable-pypy/releases

**Comment by squeaky-pl** [comment]
And 2.7 as well.

Note that I stopped uploading to bitbucket.

**Comment by wizpig64** [comment]
Thanks squeaky!
