### ISSUE TITLE
Merge the patches upstream

### ISSUE THREAD

**Issue by mattip** [squeaky-pl/portable-pypy#96]
There are a number of patches that are no longer relevant. Are you keeping them for backward compatibility? Perhaps you could add tags to the repo for the various PyPy releases and update the HEAD to match PyPy HEAD.

**Comment by mattip** [comment]
I merged much of the curses ones to PyPY, thanks

**Comment by mattip** [comment]
Looking at the ssl.py patches: they are applied to CPython's ssl.py rather than to the PyPy-specific `lib_pypy/_ssl/__init__.py` Before I try to adapt them, did you already try to modify them to work there and reject that option?

**Comment by squeaky-pl** [comment]
@mattip No, I have not tried this.

The original patch predates PyPy3 releases. It was a shameless copy, paste and diff when I started packaging PyPy3.

**Comment by mattip** [comment]
I adopted your patches a bit differently in pypy a5cd0e93d2fb and d7d279c89e1c, so that we don't modify the upstream ssl.py. What do you think? Thanks for pointing the way

**Comment by squeaky-pl** [comment]
closing since upstream already works nicely.
