### ISSUE TITLE
PyPy 7.3.0

### ISSUE THREAD

**Issue by johnthagen** [squeaky-pl/portable-pypy#97]
7.3.0 has been released: https://morepypy.blogspot.com/2019/12/pypy-730-released.html

**Comment by squeaky-pl** [comment]
As of 7.3 the general direction and some patches from Portable PyPy were adapted/incorporated into upstream. For 7.3 just go to official PyPy downloads page and grab http://pypy.org/download.html Linux x86-64 binary (64bit, built on CentOS6). They should work as well as Portable PyPy.

There are some minor differences and I will eventually provide builds in this repository as well but I don't think I will have time before 1st of January.

**Comment by johnthagen** [comment]
Oh, cool. Might be worth a note in the README explaining that portable PyPy has been upstreamed as of 7.3.
