### ISSUE TITLE
Older version Bitbucket link broken

### ISSUE THREAD

**Issue by dennisme** [squeaky-pl/portable-pypy#99]
https://bitbucket.org/squeaky/portable-pypy/downloads/

![image](https://user-images.githubusercontent.com/3649236/90681879-f8d4a780-e218-11ea-8ca8-39d429544829.png)

Is the plan to hold them somewhere else?

**Comment by squeaky-pl** [comment]
I didn't have a backup of those anywhere. I didn't realize that ending mercurial support will mean they are gonna cut off access to downloads as well.

**Comment by squeaky-pl** [comment]
Direct links such as https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.3.1-linux_x86_64-portable.tar.bz2 return 403.

**Comment by PMeira** [comment]
It seems to be archived correctly on the Wayback Machine (tried a few links): http://web.archive.org/web/20200621123545/https://bitbucket.org/squeaky/portable-pypy/downloads/

**Comment by dennisme** [comment]
> I didn't have a backup of those anywhere. I didn't realize that ending mercurial support will mean they are gonna cut off access to downloads as well.

Stuff happens, no worries

SO to the archive.org. Thanks @PMeira

**Comment by squeaky-pl** [comment]
@dennisme You can also find the downloads here: https://bitbucket-archive.softwareheritage.org/static/14/140b7b14-aa94-424e-b191-9cd3438381f7/attachments/

The original HG repository: https://bitbucket-archive.softwareheritage.org/static/14/140b7b14-aa94-424e-b191-9cd3438381f7/attachments/

Thanks @mattip from PyPy for pointing this out.

**Comment by squeaky-pl** [comment]
I updated the links in README.rst so they now point to https://bitbucket-archive.softwareheritage.org

**Comment by dennisme** [comment]
Cool appreciate it.
